name: Packer

on:
  push:
    branches: [ main ]

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validate Template
        working-directory: ./packer
        run: packer validate aws-ubuntu.pkr.hcl
        # build artifact
      - name: Build Artifact
        working-directory: ./packer
        run: packer build aws-ubuntu.pkr.hcl
        env:
          PACKER_LOG: 1
